### ISSUE TITLE
After upgrading today, icons were replaced by only one for Paypal

### ISSUE THREAD

**Issue by MarceloPedra** [vendocrat/WooCommerce-Payment-Methods#2]
Hello there. I've readed it's just a thing of this version, right? I used to show all of the cards supported by Paypal until today. Will that feature return soon? or at least can I customize the widget somehow?
Thanks in advance

**Comment by AlexanderPoellmann** [comment]
Yep, that is by design as not all credit cards are available with PayPal, Stripe & Co. I've received plenty messages regarding that so I removed them to be automatically shown.

Until I found a working solution (maybe a tiny settings page) you can use the newly introduced filters like `vendocrat_filter_wc_payment_methods` to add the desired methods.

Here's a quick example for your themes `functions.php` to add Visa & MasterCard:

``` php
function filter_payment_methods( $methods ) {
    $methods['visa'] = 'visa';
    $methods['mastercard'] = 'mastercard';

    return $methods;
}
add_filter( 'vendocrat_filter_wc_payment_methods', 'filter_payment_methods' );
```

Not quite beautiful, yet a working solution ;) Let me know if you have any suggestions for how to fix that.

**Comment by MarceloPedra** [comment]
Hi! 
Well, I noticed the "Payment Methods:" input field in the widget. That way I simply was able to enter a comma separated list of the desired cards to be shown.  That's enough for me and hope you won't retire that feature from the widget :) Won't you, right?

**Comment by AlexanderPoellmann** [comment]
My bad, forgot to mention that in first place. That field is new since the last version 1.1.2 and made specifically for that purpose. So no, I won't remove it anymore, don't worry ;)
