### ISSUE TITLE
Missing card icons on the widget

### ISSUE THREAD

**Issue by lmartins** [vendocrat/WooCommerce-Payment-Methods#3]
Hi there,

After the latest updated there some icons missing on the widget, it now only shows Bank Transfer and Paypal, while before it would also show Visa, MasterCard and some other that are supported via Paypal, would this be possible to add back?

Cheers.

**Comment by AlexanderPoellmann** [comment]
Hey Luis!
I'll have to think of a solution for that issue, as e.g. PayPal does not support the same cards in every region. That's why I had to remove the icons.

Please refer to https://github.com/vendocrat/WooCommerce-Payment-Methods/issues/2 for a temporary fix.

Btw. could you update the language file if you have some minutes?

Cheers,
Alex
